version: '3'

services:
    db:
        image: postgres:11.4
        volumes:
            - postgres-data:/var/lib/postgresql/data
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
            - media:/media
        ports:
            - 8000:8000
        depends_on:
            - db

volumes:
    postgres-data:
    media:
